# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import imageGallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=imageGallery.models.get_upload_url)),
            ],
            options={
                'verbose_name_plural': 'ImageGallery',
            },
        ),
    ]
