# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageGallery', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_array', to='imageGallery.ImageGallery'),
        ),
    ]
