# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 14:30
from __future__ import unicode_literals

import accomodations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTB_ResortFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'CTB_ResortFacilities',
            },
        ),
        migrations.CreateModel(
            name='CTB_ResortImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accomodations.models.get_upload_url)),
            ],
            options={
                'verbose_name_plural': 'CTB_ResortImages',
            },
        ),
        migrations.CreateModel(
            name='CTB_ResortOccupany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(blank=True, max_length=500)),
                ('occupany_price', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'CTB_ResortOccupany',
            },
        ),
        migrations.CreateModel(
            name='CTB_Resorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_location', models.CharField(blank=True, max_length=20)),
                ('location', models.TextField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'CTB_Resorts',
            },
        ),
        migrations.CreateModel(
            name='CTB_ResortTarrif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.CharField(blank=True, max_length=50)),
                ('checkout_time', models.CharField(blank=True, max_length=50)),
                ('CTB_Resort', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarrif', to='accomodations.CTB_Resorts')),
            ],
            options={
                'verbose_name_plural': 'CTB_ResortTarrif',
            },
        ),
        migrations.AddField(
            model_name='ctb_resortoccupany',
            name='CTB_Resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupany', to='accomodations.CTB_Resorts'),
        ),
        migrations.AddField(
            model_name='ctb_resortimages',
            name='CTB_Resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='accomodations.CTB_Resorts'),
        ),
        migrations.AddField(
            model_name='ctb_resortfacilities',
            name='CTB_Resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='accomodations.CTB_Resorts'),
        ),
    ]
