# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctb_resortoccupany',
            old_name='occupany_price',
            new_name='occupancy_price',
        ),
        migrations.AlterField(
            model_name='ctb_resortoccupany',
            name='CTB_Resort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupancy', to='accomodations.CTB_Resorts'),
        ),
    ]
