# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_auto_20180315_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredHotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('contact_no', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Registered Hotels',
            },
        ),
    ]
