# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 17:37
from __future__ import unicode_literals

import accomodations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0004_registeredtraveloperators'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitywiseHotelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to=accomodations.models.get_pdf_upload_url)),
            ],
            options={
                'verbose_name_plural': 'City Wise Hotel Pdfs',
            },
        ),
    ]
