# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimages',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.AddField(
            model_name='places',
            name='major_attraction',
            field=models.BooleanField(default=False),
        ),
    ]
