# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0002_auto_20180307_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='places',
            name='long',
        ),
    ]
