# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0003_auto_20180307_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='places',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
