# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0004_auto_20180307_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='category',
            field=models.CharField(blank=True, choices=[('waterfall', 'Waterfall'), ('other', 'Other')], max_length=255),
        ),
    ]
