# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 16:26
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('touristSpots', '0005_places_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'PlaceReviews',
            },
        ),
        migrations.AddField(
            model_name='places',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.AddField(
            model_name='places',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0000'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='places',
            name='category',
            field=models.CharField(blank=True, choices=[('cave', 'Cave'), ('dam', 'Dam'), ('hill', 'Hill'), ('monument', 'Monument'), ('museum', 'Museum'), ('national_park_and_bioshphere_reserve', 'National Park & Biosphere Reserve'), ('religious_attraction', 'Religious Attraction'), ('tiger_reserve', 'Tiger Reserve'), ('waterfall', 'Waterfall'), ('wildfile_sanctuary', 'Wildlife Sanctuary'), ('other', 'Other')], max_length=255),
        ),
        migrations.AddField(
            model_name='placereviews',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_place', to='touristSpots.Places'),
        ),
        migrations.AddField(
            model_name='placereviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
