# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0006_auto_20180313_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereviews',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_place', to='touristSpots.Places'),
        ),
    ]
