# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0007_auto_20180314_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
