# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0008_auto_20180314_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='places',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='touristSpots.Places'),
        ),
    ]
