# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import touristSpots.models


class Migration(migrations.Migration):

    dependencies = [
        ('touristSpots', '0010_auto_20180314_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='CategoryImages/defaultImage/defaultCategoryImage.jpg', upload_to=touristSpots.models.get_category_upload_url),
        ),
    ]
