# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:55
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
