# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import userAccounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0002_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='userProfileImages/default/defaultProfileImage.png', upload_to=userAccounts.models.get_upload_url),
        ),
    ]
