# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 12:26
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0003_auto_20180306_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
